 DockerUI:
  labels:
    io.rancher.container.pull_image: always
    rap.port: '9000'
    rap.le_host: ${DOCKERUI_HOST}
    rap.le_mail: ${LE_EMAIL}
    rap.host: ${DOCKERUI_HOST}
  tty: true
  image: uifd/ui-for-docker
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /data
  net: bridge
 Portainer:
  environment:
    VIRTUAL_HOST: ${PORTAINER_HOST}
    VIRTUAL_PORT: '9000'
    LETSENCRYPT_HOST: ${PORTAINER_HOST}
    LETSENCRYPT_EMAIL: ${LE_EMAIL}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: portainer/portainer
  net: bridge
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock