version: '2'
services:
 DockerUI:
  environment:
    VIRTUAL_HOST: ${DOCKERUI_HOST}
    VIRTUAL_PORT: '9000'
    LETSENCRYPT_HOST: ${DOCKERUI_HOST}
    LETSENCRYPT_EMAIL: ${LE_EMAIL}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: uifd/ui-for-docker
  network_mode: bridge
  privileged: true
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  - /data
  net: bridge
 Portainer:
  environment:
    VIRTUAL_HOST: ${DOCKERUI_HOST}
    VIRTUAL_PORT: '9000'
    LETSENCRYPT_HOST: ${DOCKERUI_HOST}
    LETSENCRYPT_EMAIL: ${LE_EMAIL}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: portainer/portainer
  network_mode: bridge
  volumes:
  - /var/run/docker.sock:/var/run/docker.sock
  net: bridge