stages:
  - build
  - test
  - deploy

before_script:
    - if [ $CI_BUILD_REF_NAME == "master" ]; then tag="latest"; else tag=$CI_BUILD_REF_NAME; fi
    - echo $CI_COMMIT_TAG
    - echo "Testt"

build-image:
 image: docker
 stage: build
 services:
  - docker:dind
 script:
    - echo $CI_COMMIT_TAG
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com/adi90x
    - docker build -t registry.gitlab.com/adi90x/arbnode:$tag .
    - docker push registry.gitlab.com/adi90x/arbnode
 