stages:
  - build
  - test
  - deploy

before_script:
    - if [ $CI_BUILD_REF_NAME == "master" ]; then tag="latest"; else tag=$CI_BUILD_REF_NAME; fi
    - echo $CI_COMMIT_TAG
    - echo "Test1"

build-image:
 image: docker
 stage: build
 services:
  - docker:dind
 script:
    - echo $CI_COMMIT_TAG