stages:
  - build
  - test
  - deploy

before_script:
    - if [ $CI_BUILD_REF_NAME == "master" ]; then tag="latest"; else tag=$CI_BUILD_REF_NAME; fi
    - echo $CI_COMMIT_TAG
    - echo $CI_COMMIT_REF_SLUG
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_COMMIT_SHA
    - echo $CI_COMMIT_SHA | cut -c -5
    - arbnode_version=`echo $CI_COMMIT_SHA | cut -c -7`
    - echo $arbnode_version

build-image:
 image: docker
 stage: build
 services:
  - docker:dind
 script:
    - echo $arbnode_version
    - echo $CI_COMMIT_TAG
    - echo $CI_COMMIT_REF_NAMEgi