smtp:
  scale: 1
antivirus:
  scale: 1
webmail:
  scale: 1
redis:
  scale: 1
imap:
  scale: 1
http:
  scale: 1
antispam:
  scale: 1
admin:
  scale: 1
milter:
  scale: 1
fetchmail:
  scale: 1
.catalog:
 name: "Version Initial"
 version: "0.0.1"
 questions:
  - variable: VIRTUAL_HOST
    label: "Mail Server Virtual Host"
    default: "mail.wheretogo.fr"
    required: true
    type: string
  - variable: VIRTUAL_PORT
    label: "Mail Server Virtual Port"
    default: "443"
    required: true
    type: string
  - variable: VIRTUAL_PROTO
    label: "Mail Server Virtual Proto"
    default: "https"
    required: true
    type: string  
  - variable: LETSENCRYPT_EMAIL
    label: "Lets's Encrypt Email to setup SSL"
    default: "amaurel90@gmail.com"
    required: true
    type: string
  - variable: ROOT
    label: "Root Path for Mailu on host"
    default: "/home/adrienm/data/mailu"
    required: true
    type: string
  - variable: VERSION
    label: "Mailu Version (stable,latest,...)"
    default: "latest"
    required: true
    type: string
  - variable: SECRET_KEY
    label: "Mailu Secret Key should be random & 16 characters"
    default: "060190adrienmadi"
    required: true
    type: string
  - variable: BIND_ADDRESS
    label: "Mailu address where listening should bind"
    default: "0.0.0.0"
    required: true
    type: string
  - variable: DOMAIN
    label: "Exposed mail domain"
    default: "wheretogo.fr"
    required: true
    type: string
  - variable: HOSTNAME
    label: "Exposed mail-server hostname"
    default: "mail.wheretogo.fr"
    required: true
    type: string
  - variable: POSTMASTER
    label: "Postmaster local part"
    default: "admin"
    required: true
    type: string
  - variable: COMPOSE_PROJECT_NAME
    label: "Docker-compose project name"
    default: "mail"
    required: true
    type: string
  - variable: FRONTEND
    label: "Frontend web server"
    default: "nginx"
    type: enum   
    options: 
        - "nginx"
        - "none"
  - variable: WEBMAIL
    label: "Webmail server type"
    default: "roundcube"
    type: enum   
    options: 
        - "roundcube"
        - "rainloop"
        - "none"
  - variable: EXPOSE_ADMIN
    label: "Expose administration"
    default: "yes"
    type: enum   
    options: 
        - "yes"
        - "no"
  - variable: ENABLE_CERTBOT
    label: "Use Certbot to generate a TLS cert"
    default: "False"
    type: enum   
    options: 
        - "True"
        - "False"
  - variable: MESSAGE_SIZE_LIMIT
    label: "Message size limit in bytes"
    default: "50000000"
    type: string
  - variable: RELAYNETS
    label: "Networks granted relay permissions"
    default: "172.16.0.0/12,10.32.0.0/12"
    type: string
  - variable: RELAYHOST
    label: "Host to relay (should be empty to be safe)"
    default: ""
    type: string
  - variable: FETCHMAIL_DELAY
    label: "Fetchmail delay"
    default: "600"
    type: string
  - variable: DEBUG
    label: "Enable Debug"
    default: "False"
    type: enum   
    options: 
        - "True"
        - "False"
    