GitlabRunner:
    privileged: true
    image: gitlab/gitlab-runner:latest
    stdin_open: true
    network_mode: host
    volumes:
    - ${HOST_PATH}:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    pid: host
    labels:
      io.rancher.container.pull_image: always