Iodined:
  ports:
  - ${PORT}:53/udp
  environment:
    IODINE_PASS: ${PASS}
    IODINE_HOST: ${HOST}
    IODINE_IP: ${IP}
  labels:
    io.rancher.container.pull_image: always
  image: adamant/iodine
  devices:
  - /dev/net/tun:/dev/net/tun:rwm
  net: bridge
  cap_add:
  - NET_ADMIN
