version: '2'
services:
  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_PASSWORD: '060190'
    volumes:
    - ${PATH}/wp-content/:/var/www/html/wp-content
    ports:
    - 90:80/tcp
    labels:
      rap.host: wp.wheretogo.fr,www.menjuc.com,menjuc.com
  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: '060190'
    volumes:
    - ${PATH}/mysql:/var/lib/mysql