CreateClient:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  command:
  - easyrsa
  - build-client-full
  - ${USER}
  - nopass
  image: kylemanna/openvpn
  volumes:
  - ${PATH}:/etc/openvpn
Server:
  ports:
  - ${PORT}:1194/udp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: kylemanna/openvpn
  volumes:
  - ${PATH}:/etc/openvpn
  net: bridge
  cap_add:
  - NET_ADMIN
RecupClientConfig:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.start_once: 'true'
  tty: true
  command:
  - ovpn_getclient_all
  image: kylemanna/openvpn
  volumes:
  - ${PATH}:/etc/openvpn
