name: Nginx Proxy
description: Setup Nginx Proxy for virtual host and auto Let's encrypt
version: 0
category: Perso
maintainer: AdrienM
license: MIT
projectURl: "https://github.com/JrCs/docker-letsencrypt-nginx-proxy-companion"