version: '2'
services:
  Proxy:
    image: adi90x/rancher-active-proxy:dev
    environment:
      DEFAULT_HOST: $(DEFAULT_HOST)
      DEFAULT_EMAIL: $(DEFAULT_EMAIL)
    stdin_open: true
    volumes:
    - $(PATH)/html:/usr/share/nginx/html
    - $(PATH)/certs:/etc/nginx/certs
    - $(PATH)/htpasswd:/etc/nginx/htpasswd
    - $(PATH)/vhost.d:/etc/nginx/vhost.d
    - $(PATH)/conf.d:/etc/nginx/conf.d
    - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    ports:
    - 80:80/tcp
    - 443:443/tcp
    labels:
      io.rancher.container.pull_image: always