.catalog:
 name: "Initial Version"
 version: "v0.0.0"
 questions:
    - variable: PATH
      label: "Path to save config on host"
      default: "/home/adrienm/data/rancher-active-proxy"
      type: string
    - variable: DEFAULT_HOST
      label: "Default Virtual Host to use"
      type: string
    - variable: EMAIL
      label: "Default Email to use for Letsencrypt"
      default: "amaurel90@gmail.com"
      type: string
    - variable: CRON
      label: "Auto renew cron like setup"
      default: "0 2 * * *"
      type: string
    - variable: DEBUG
      label: "Set to true to enable debug"
      default: "False"
      type: string
