network:
    version: 2
    renderer: networkd
    ethernets:
       enp1s0:
           dhcp4: no
           addresses: [192.168.0.25/24]
           gateway4: 192.168.0.1
           nameservers:
              addresses: [8.8.8.8,8.8.4.4]
              search: [bubulette]
