name: Mail Server
description: "Create a Mail Serveur based on MailServer"
version: v0.0.0
category: Perso
maintainer: AdrienM
license: Apache 2.0
projectURl: "https://github.com/hardware/mailserver"
